repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/nholuongut/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        name: Markdownlint

  - repo: https://github.com/nholuongut/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        name: Shellcheck

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Python black code formatter
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Python flake8
        args:
          - --max-line-length=88
          - --ignore=E501,W503
